# Generated by Django 5.0.8 on 2024-12-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0005_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
