# Generated by Django 5.0.8 on 2024-12-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0007_remove_reward_description_remove_reward_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='product_images/')),
            ],
        ),
    ]
