# Generated by Django 5.0.8 on 2025-02-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0009_visit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_name', models.CharField(max_length=255)),
                ('points', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
