# Generated by Django 5.0.8 on 2025-02-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0010_pointallocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointallocation',
            name='point_name',
            field=models.CharField(choices=[('vist_salon', 'Client Visiting Salon'), ('user_create_profile', 'Clients creates and new profile'), ('reward_referrer', 'Reward the referrer')], max_length=255),
        ),
    ]
