# Generated by Django 5.0.8 on 2025-02-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0011_alter_pointallocation_point_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
